version: '3.8'
services:
  db:
    image: mysql:latest
    restart: always
    container_name: db
    environment:
      - MYSQL_DATABASE=project_apu
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  # app:
  #   container_name: app
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - db
  #   ports:
  #     - '3000:3000'
  #   restart: always
  #   environment:
  #     - PORT=3000
  #     - DATABASE_URL="mysql://root:root_password@localhost:3306/project_apu"
  #     - JWT_SECRET="MyJwtSup3rSecr7e!!@212"

volumes:
  mysql_data: